databases:
  - name: motorcycle_booking_db
    databaseName: motorcycle_booking_db
    user: motorcycle_booking_db_user

services:
  - type: web
    name: motorcyclebooking
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motorcycle_booking_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false